### ISSUE TITLE
Duplex.EventSource

### ISSUE THREAD

**Issue by amarkatti** [tabrath/Duplex.Signalhub#1]
Hello,
when I try to build the solution throws me error that duplex.eventsource does not exist. What s this ? Is this another class or nugget package?
where do I find the contents of this namespace.

**Comment by tabrath** [comment]
It's [here](https://github.com/tabrath/Duplex.EventSource).

**Comment by amarkatti** [comment]
what is Duplex.SignalHub ?? what does it do?

**Comment by tabrath** [comment]
It's a C# port of [this](https://github.com/mafintosh/signalhub).
